version: '3.8'

services:
  backend:
    # Replace "yourusername" with your actual Docker Hub username
    image: mdk7866/farmhelp-backend:latest
    container_name: farmhelp_backend
    ports:
      - "8000:8000"
    env_file:
      - .env.backend
    restart: always

  frontend:
    # Replace "yourusername" with your actual Docker Hub username
    image: mdk7866/farmhelp-frontend:latest
    container_name: farmhelp_frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.frontend
    depends_on:
      - backend
    restart: always
